/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_md_5_bungee_jni_cipher_NativeCipherImpl */

#ifndef _Included_net_md_5_bungee_jni_cipher_NativeCipherImpl
#define _Included_net_md_5_bungee_jni_cipher_NativeCipherImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_md_5_bungee_jni_cipher_NativeCipherImpl
 * Method:    init
 * Signature: (Z[B)J
 */
JNIEXPORT jlong JNICALL Java_net_md_15_bungee_jni_cipher_NativeCipherImpl_init
  (JNIEnv *, jobject, jboolean, jbyteArray);

/*
 * Class:     net_md_5_bungee_jni_cipher_NativeCipherImpl
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_md_15_bungee_jni_cipher_NativeCipherImpl_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_md_5_bungee_jni_cipher_NativeCipherImpl
 * Method:    cipher
 * Signature: (JJJI)V
 */
JNIEXPORT void JNICALL Java_net_md_15_bungee_jni_cipher_NativeCipherImpl_cipher
  (JNIEnv *, jobject, jlong, jlong, jlong, jint);

// Waterdog start
/*
 * Class:     network_ycc_waterdog_jni_NativeHashImpl
 * Method:    update
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_net_md_15_bungee_jni_cipher_NativeCipherImpl_update__JB
  (JNIEnv *, jobject, jlong, jbyte);

/*
 * Class:     network_ycc_waterdog_jni_NativeHashImpl
 * Method:    updateLongLE
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_net_md_15_bungee_jni_cipher_NativeCipherImpl_updateLongLE
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     network_ycc_waterdog_jni_NativeHashImpl
 * Method:    update
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_net_md_15_bungee_jni_cipher_NativeCipherImpl_update__JJI
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     network_ycc_waterdog_jni_NativeHashImpl
 * Method:    digest
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_net_md_15_bungee_jni_cipher_NativeCipherImpl_digest
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     network_ycc_waterdog_jni_NativeHashImpl
 * Method:    staticPEHash
 * Signature: (JJIJJ)V
 */
JNIEXPORT void JNICALL Java_net_md_15_bungee_jni_cipher_NativeCipherImpl_staticPEHash
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jlong);
// Waterdog end

#ifdef __cplusplus
}
#endif
#endif
