/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_ycc_waterdog_jni_NativeHashImpl */

#ifndef _Included_network_ycc_waterdog_jni_NativeHashImpl
#define _Included_network_ycc_waterdog_jni_NativeHashImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     network_ycc_waterdog_jni_NativeHashImpl
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_network_ycc_waterdog_jni_NativeHashImpl_init
  (JNIEnv *, jobject);

/*
 * Class:     network_ycc_waterdog_jni_NativeHashImpl
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_network_ycc_waterdog_jni_NativeHashImpl_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     network_ycc_waterdog_jni_NativeHashImpl
 * Method:    update
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_network_ycc_waterdog_jni_NativeHashImpl_update__JB
  (JNIEnv *, jobject, jlong, jbyte);

/*
 * Class:     network_ycc_waterdog_jni_NativeHashImpl
 * Method:    updateLongLE
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_network_ycc_waterdog_jni_NativeHashImpl_updateLongLE
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     network_ycc_waterdog_jni_NativeHashImpl
 * Method:    update
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_network_ycc_waterdog_jni_NativeHashImpl_update__JJI
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     network_ycc_waterdog_jni_NativeHashImpl
 * Method:    digest
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_network_ycc_waterdog_jni_NativeHashImpl_digest
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     network_ycc_waterdog_jni_NativeHashImpl
 * Method:    staticPEHash
 * Signature: (JJIJJ)V
 */
JNIEXPORT void JNICALL Java_network_ycc_waterdog_jni_NativeHashImpl_staticPEHash
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
